name: Executa testes

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Faz pull do repositório
        uses: actions/checkout@v4

      - name: Configura node JS
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Instala Dependências
        run: npm install

      - name: Executa Testes
        run: npm run test

      - name: Comenta cobertura de testes
        uses: slavcodev/coverage-monitor-action@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage/clover.xml"
          threshold_alert: 80
          threshold_warning: 90
          threshold_metric: "lines"
