name: Executa testes

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write
  checks: write
  pull-requests: write
  statuses: write

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Faz pull do repositório
        uses: actions/checkout@v4

      - name: Configura node JS
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Instala Dependências
        run: npm install

      - name: Executa Testes
        run: npm run test

      - name: Comenta cobertura de testes
        uses: slavcodev/coverage-monitor-action@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage/clover.xml"
          threshold_alert: 80
          threshold_warning: 90
          threshold_metric: "lines"

  deploy:
    runs-on: ubuntu-latest
    needs: testes
    if: github.ref == 'refs/heads/main'
    environment:
      name: render
      url: https://integrador-back-uk8c.onrender.com/health

    steps:
      - name: Aguarda deploy para o render
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: integrador-back
          retries: 3
          wait: 10000
          sleep: 5000
